name: React CI/CD with Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: dockerfile
    container:
      image: my-react-app:latest # Use custom base image

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Deploy to Server
        run: |
          mkdir -p /var/www/react-app
          cp -r build/* /var/www/react-app/
